elasticsearch:
  hosts: ["http://localhost:9200"]
  username: "username"
  password: "password"
  verify_certs: false

indexes:
  - wbs_resources
  - wbs_tasks
  - wbs_info
  - wbs_calendars

# For custom properties definition
extends:
  tasks:
    - type: date
      id: Deadline
      name: tasks deadline

  resources:

tjp_output_path:
  tjp_outputs/exports.tjp
