# Connection properties
elasticsearch:
  hosts: [ "http://127.0.0.1:9200" ]
  username: "password"
  password: "username"
  verify_certs: false
# End of connection properties




# Declaring elastic indexes names
indexes:
  - wbs_resources
  - wbs_tasks
  - wbs_info
  - wbs_calendars
# End of indexes



# Defining scenarios
scenarios:
  - id: delayed
    name: starts with delay
# End of scenarios



# Accounts setting
accounts:
  creation_mode:
    for_all_tasks: False # if is False, then accounts will be created just for top-level tasks

# End of accounts



# Defining reports
reports:
  text_report:
    include: true
    id: projectReports
    name: project gantt chart
    resource_report: true  # Boolean
    task_report: true   # Boolean
    formats:
      - html
      - csv

  resource_report:
    include: false
    id: resourcesReports
    name: resources reports
    formats:
      - html

    columns:
      - id
      - name
      - rate
      - Type
      - AccrueAt
      - flags
      - OvertimeCost
      - efficiency
      - WorkinghoursChange
      - BaseCost
      - ActualCost
      - Availability
      - managers




  task_report:
    include: false
    id: taskReports
    name: tasks reports
    resources:
      show: true # Boolean
      sort_by: name
      ASC: true # Boolean

    formats:
      - html

    columns:
      - id
      - name
      - start
      - end
      - minstart
      - maxstart
      - minend
      - maxend
      - duration
      - effort
      - Deadline
      - priority
      - note

  account_report:
    include: false
    id: accountReports
    name: accounts reports
    formats:
      - html

    columns:
      - id
      - name
# End of reports





# For custom properties definition
extends:
  tasks:
    - type: date
      id: Deadline
      name: Deadline

  resources:
    - type: text
      id: Type
      name: Type

    - type: number
      id: OvertimeCost
      name: Overtime Cost

    - type: date
      id: Availability
      name: Availability Date

    - type: date
      id: WorkinghoursChange
      name: Workinghours Change

    - type: number
      id: BaseCost
      name: Base Cost

    - type: number
      id: ActualCost
      name: Actual Cost

    - type: text
      id: AccrueAt
      name: Accrue at
# End of custom properties definition


# Error handling settings
exceptions:
  save_logs_in_db: true
# End of errors

# Directories paths
paths:
  tjp_output: tjp_outputs/project.tjp
  templates: templates/
  exports: exports/
# End of directories paths